/*
 * Copyright 2012 Diamond Light Source Ltd.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.icat3.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ICAT", targetNamespace = "client.icat3.uk")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICAT {


    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns java.lang.String
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.LoginResponse")
    public String login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param username
     * @param lifetime
     * @param password
     * @return
     *     returns java.lang.String
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loginLifetime", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.LoginLifetime")
    @ResponseWrapper(localName = "loginLifetimeResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.LoginLifetimeResponse")
    public String loginLifetime(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "lifetime", targetNamespace = "")
        int lifetime)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param investigationId
     * @param sample
     * @return
     *     returns uk.icat3.client.Sample
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addSample", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddSample")
    @ResponseWrapper(localName = "addSampleResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddSampleResponse")
    public Sample addSample(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "sample", targetNamespace = "")
        Sample sample,
        @WebParam(name = "investigationId", targetNamespace = "")
        Long investigationId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.LogoutResponse")
    public boolean logout(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param sampleParameter
     * @param investigationId
     * @return
     *     returns uk.icat3.client.SampleParameter
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addSampleParameter", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddSampleParameter")
    @ResponseWrapper(localName = "addSampleParameterResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddSampleParameterResponse")
    public SampleParameter addSampleParameter(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "sampleParameter", targetNamespace = "")
        SampleParameter sampleParameter,
        @WebParam(name = "investigationId", targetNamespace = "")
        Long investigationId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param investigationId
     * @param publication
     * @return
     *     returns uk.icat3.client.Publication
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addPublication", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddPublication")
    @ResponseWrapper(localName = "addPublicationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddPublicationResponse")
    public Publication addPublication(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "publication", targetNamespace = "")
        Publication publication,
        @WebParam(name = "investigationId", targetNamespace = "")
        Long investigationId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param keyword
     * @param investigationId
     * @return
     *     returns uk.icat3.client.Keyword
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addKeyword", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddKeyword")
    @ResponseWrapper(localName = "addKeywordResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddKeywordResponse")
    public Keyword addKeyword(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "keyword", targetNamespace = "")
        Keyword keyword,
        @WebParam(name = "investigationId", targetNamespace = "")
        Long investigationId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param investigator
     * @param investigationId
     * @return
     *     returns uk.icat3.client.Investigator
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addInvestigator", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddInvestigator")
    @ResponseWrapper(localName = "addInvestigatorResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddInvestigatorResponse")
    public Investigator addInvestigator(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "investigator", targetNamespace = "")
        Investigator investigator,
        @WebParam(name = "investigationId", targetNamespace = "")
        Long investigationId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param investigationId
     * @return
     *     returns uk.icat3.client.Investigation
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInvestigation", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetInvestigation")
    @ResponseWrapper(localName = "getInvestigationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetInvestigationResponse")
    public Investigation getInvestigation(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "investigationId", targetNamespace = "")
        Long investigationId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param investigationInclude
     * @param investigationId
     * @return
     *     returns uk.icat3.client.Investigation
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInvestigationIncludes", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetInvestigationIncludes")
    @ResponseWrapper(localName = "getInvestigationIncludesResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetInvestigationIncludesResponse")
    public Investigation getInvestigationIncludes(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "investigationId", targetNamespace = "")
        Long investigationId,
        @WebParam(name = "investigationInclude", targetNamespace = "")
        InvestigationInclude investigationInclude)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datasetId
     * @return
     *     returns uk.icat3.client.Dataset
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDataset", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetDataset")
    @ResponseWrapper(localName = "getDatasetResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetDatasetResponse")
    public Dataset getDataset(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datasetId", targetNamespace = "")
        Long datasetId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param datasetInclude
     * @param sessionId
     * @param datasetId
     * @return
     *     returns uk.icat3.client.Dataset
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatasetIncludes", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetDatasetIncludes")
    @ResponseWrapper(localName = "getDatasetIncludesResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetDatasetIncludesResponse")
    public Dataset getDatasetIncludes(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datasetId", targetNamespace = "")
        Long datasetId,
        @WebParam(name = "datasetInclude", targetNamespace = "")
        DatasetInclude datasetInclude)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datafileId
     * @return
     *     returns uk.icat3.client.Datafile
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatafile", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetDatafile")
    @ResponseWrapper(localName = "getDatafileResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetDatafileResponse")
    public Datafile getDatafile(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datafileId", targetNamespace = "")
        Long datafileId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param dataFileParameter
     * @param sessionId
     * @param datafileId
     * @return
     *     returns uk.icat3.client.DatafileParameter
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addDataFileParameter", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddDataFileParameter")
    @ResponseWrapper(localName = "addDataFileParameterResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddDataFileParameterResponse")
    public DatafileParameter addDataFileParameter(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "dataFileParameter", targetNamespace = "")
        DatafileParameter dataFileParameter,
        @WebParam(name = "datafileId", targetNamespace = "")
        Long datafileId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param advancedSearchDetails
     * @return
     *     returns java.util.List<uk.icat3.client.Investigation>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByAdvanced", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByAdvanced")
    @ResponseWrapper(localName = "searchByAdvancedResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByAdvancedResponse")
    public List<Investigation> searchByAdvanced(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "advancedSearchDetails", targetNamespace = "")
        AdvancedSearchDetails advancedSearchDetails)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param startIndex
     * @param numberOfResults
     * @param sessionId
     * @param advancedSearchDetails
     * @return
     *     returns java.util.List<uk.icat3.client.Investigation>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByAdvancedPagination", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByAdvancedPagination")
    @ResponseWrapper(localName = "searchByAdvancedPaginationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByAdvancedPaginationResponse")
    public List<Investigation> searchByAdvancedPagination(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "advancedSearchDetails", targetNamespace = "")
        AdvancedSearchDetails advancedSearchDetails,
        @WebParam(name = "startIndex", targetNamespace = "")
        int startIndex,
        @WebParam(name = "numberOfResults", targetNamespace = "")
        int numberOfResults)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param keywords
     * @param sessionId
     * @return
     *     returns java.util.List<uk.icat3.client.Investigation>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByKeywords", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByKeywords")
    @ResponseWrapper(localName = "searchByKeywordsResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByKeywordsResponse")
    public List<Investigation> searchByKeywords(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "keywords", targetNamespace = "")
        List<String> keywords)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param startIndex
     * @param numberOfResults
     * @param sessionId
     * @param keywordDetails
     * @return
     *     returns java.util.List<uk.icat3.client.Investigation>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByKeywordsAll", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByKeywordsAll")
    @ResponseWrapper(localName = "searchByKeywordsAllResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByKeywordsAllResponse")
    public List<Investigation> searchByKeywordsAll(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "keywordDetails", targetNamespace = "")
        KeywordDetails keywordDetails,
        @WebParam(name = "startIndex", targetNamespace = "")
        int startIndex,
        @WebParam(name = "numberOfResults", targetNamespace = "")
        int numberOfResults)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns java.util.List<uk.icat3.client.Investigation>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMyInvestigations", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetMyInvestigations")
    @ResponseWrapper(localName = "getMyInvestigationsResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetMyInvestigationsResponse")
    public List<Investigation> getMyInvestigations(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param investigationInclude
     * @return
     *     returns java.util.List<uk.icat3.client.Investigation>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMyInvestigationsIncludes", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetMyInvestigationsIncludes")
    @ResponseWrapper(localName = "getMyInvestigationsIncludesResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetMyInvestigationsIncludesResponse")
    public List<Investigation> getMyInvestigationsIncludes(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "investigationInclude", targetNamespace = "")
        InvestigationInclude investigationInclude)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param startIndex
     * @param numberOfResults
     * @param sessionId
     * @param investigationInclude
     * @return
     *     returns java.util.List<uk.icat3.client.Investigation>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMyInvestigationsIncludesPagination", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetMyInvestigationsIncludesPagination")
    @ResponseWrapper(localName = "getMyInvestigationsIncludesPaginationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetMyInvestigationsIncludesPaginationResponse")
    public List<Investigation> getMyInvestigationsIncludesPagination(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "investigationInclude", targetNamespace = "")
        InvestigationInclude investigationInclude,
        @WebParam(name = "startIndex", targetNamespace = "")
        int startIndex,
        @WebParam(name = "numberOfResults", targetNamespace = "")
        int numberOfResults)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param userSearch
     * @param sessionId
     * @return
     *     returns java.util.List<uk.icat3.client.Investigation>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByUserID", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByUserID")
    @ResponseWrapper(localName = "searchByUserIDResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByUserIDResponse")
    public List<Investigation> searchByUserID(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "userSearch", targetNamespace = "")
        String userSearch)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param startIndex
     * @param numberOfResults
     * @param userSearch
     * @param sessionId
     * @return
     *     returns java.util.List<uk.icat3.client.Investigation>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByUserIDPagination", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByUserIDPagination")
    @ResponseWrapper(localName = "searchByUserIDPaginationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByUserIDPaginationResponse")
    public List<Investigation> searchByUserIDPagination(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "userSearch", targetNamespace = "")
        String userSearch,
        @WebParam(name = "startIndex", targetNamespace = "")
        int startIndex,
        @WebParam(name = "numberOfResults", targetNamespace = "")
        int numberOfResults)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param surname
     * @return
     *     returns java.util.List<uk.icat3.client.Investigation>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByUserSurname", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByUserSurname")
    @ResponseWrapper(localName = "searchByUserSurnameResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByUserSurnameResponse")
    public List<Investigation> searchByUserSurname(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "surname", targetNamespace = "")
        String surname)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param startIndex
     * @param numberOfResults
     * @param sessionId
     * @param surname
     * @return
     *     returns java.util.List<uk.icat3.client.Investigation>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByUserSurnamePagination", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByUserSurnamePagination")
    @ResponseWrapper(localName = "searchByUserSurnamePaginationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByUserSurnamePaginationResponse")
    public List<Investigation> searchByUserSurnamePagination(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "surname", targetNamespace = "")
        String surname,
        @WebParam(name = "startIndex", targetNamespace = "")
        int startIndex,
        @WebParam(name = "numberOfResults", targetNamespace = "")
        int numberOfResults)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listInstruments", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ListInstruments")
    @ResponseWrapper(localName = "listInstrumentsResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ListInstrumentsResponse")
    public List<String> listInstruments(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns java.util.List<uk.icat3.client.IcatRole>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listRoles", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ListRoles")
    @ResponseWrapper(localName = "listRolesResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ListRolesResponse")
    public List<IcatRole> listRoles(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listInvestigationTypes", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ListInvestigationTypes")
    @ResponseWrapper(localName = "listInvestigationTypesResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ListInvestigationTypesResponse")
    public List<String> listInvestigationTypes(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns java.util.List<uk.icat3.client.Parameter>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listParameters", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ListParameters")
    @ResponseWrapper(localName = "listParametersResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ListParametersResponse")
    public List<Parameter> listParameters(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param xml
     * @return
     *     returns java.util.List<java.lang.Long>
     * @throws InsufficientPrivilegesException_Exception
     * @throws ICATAPIException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingestMetadata", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.IngestMetadata")
    @ResponseWrapper(localName = "ingestMetadataResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.IngestMetadataResponse")
    public List<Long> ingestMetadata(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "xml", targetNamespace = "")
        String xml)
        throws ICATAPIException_Exception, InsufficientPrivilegesException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param investigationIds
     * @param userId
     * @param investigationInclude
     * @return
     *     returns java.util.List<uk.icat3.client.Investigation>
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInvestigationsIncludes", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetInvestigationsIncludes")
    @ResponseWrapper(localName = "getInvestigationsIncludesResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetInvestigationsIncludesResponse")
    public List<Investigation> getInvestigationsIncludes(
        @WebParam(name = "userId", targetNamespace = "")
        String userId,
        @WebParam(name = "investigationIds", targetNamespace = "")
        List<Long> investigationIds,
        @WebParam(name = "investigationInclude", targetNamespace = "")
        InvestigationInclude investigationInclude)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param investigation
     * @return
     *     returns uk.icat3.client.Investigation
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createInvestigation", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.CreateInvestigation")
    @ResponseWrapper(localName = "createInvestigationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.CreateInvestigationResponse")
    public Investigation createInvestigation(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "investigation", targetNamespace = "")
        Investigation investigation)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param investigationId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeInvestigation", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveInvestigation")
    @ResponseWrapper(localName = "removeInvestigationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveInvestigationResponse")
    public void removeInvestigation(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "investigationId", targetNamespace = "")
        Long investigationId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param investigationId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteInvestigation", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteInvestigation")
    @ResponseWrapper(localName = "deleteInvestigationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteInvestigationResponse")
    public void deleteInvestigation(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "investigationId", targetNamespace = "")
        Long investigationId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param investigaion
     * @param sessionId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifyInvestigation", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifyInvestigation")
    @ResponseWrapper(localName = "modifyInvestigationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifyInvestigationResponse")
    public void modifyInvestigation(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "investigaion", targetNamespace = "")
        Investigation investigaion)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param keywordPK
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeKeyword", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveKeyword")
    @ResponseWrapper(localName = "removeKeywordResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveKeywordResponse")
    public void removeKeyword(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "keywordPK", targetNamespace = "")
        KeywordPK keywordPK)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param keywordPK
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteKeyword", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteKeyword")
    @ResponseWrapper(localName = "deleteKeywordResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteKeywordResponse")
    public void deleteKeyword(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "keywordPK", targetNamespace = "")
        KeywordPK keywordPK)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param publicationId
     * @param sessionId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removePublication", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemovePublication")
    @ResponseWrapper(localName = "removePublicationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemovePublicationResponse")
    public void removePublication(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "publicationId", targetNamespace = "")
        Long publicationId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param publicationId
     * @param sessionId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deletePublication", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeletePublication")
    @ResponseWrapper(localName = "deletePublicationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeletePublicationResponse")
    public void deletePublication(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "publicationId", targetNamespace = "")
        Long publicationId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param publication
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifyPublication", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifyPublication")
    @ResponseWrapper(localName = "modifyPublicationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifyPublicationResponse")
    public void modifyPublication(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "publication", targetNamespace = "")
        Publication publication)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param investigatorPK
     * @param sessionId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeInvestigator", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveInvestigator")
    @ResponseWrapper(localName = "removeInvestigatorResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveInvestigatorResponse")
    public void removeInvestigator(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "investigatorPK", targetNamespace = "")
        InvestigatorPK investigatorPK)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param investigator
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifyInvestigator", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifyInvestigator")
    @ResponseWrapper(localName = "modifyInvestigatorResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifyInvestigatorResponse")
    public void modifyInvestigator(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "investigator", targetNamespace = "")
        Investigator investigator)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param investigatorPK
     * @param sessionId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteInvestigator", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteInvestigator")
    @ResponseWrapper(localName = "deleteInvestigatorResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteInvestigatorResponse")
    public void deleteInvestigator(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "investigatorPK", targetNamespace = "")
        InvestigatorPK investigatorPK)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param sampleId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeSample", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveSample")
    @ResponseWrapper(localName = "removeSampleResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveSampleResponse")
    public void removeSample(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "sampleId", targetNamespace = "")
        Long sampleId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param sampleId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSample", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteSample")
    @ResponseWrapper(localName = "deleteSampleResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteSampleResponse")
    public void deleteSample(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "sampleId", targetNamespace = "")
        Long sampleId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param sample
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifySample", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifySample")
    @ResponseWrapper(localName = "modifySampleResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifySampleResponse")
    public void modifySample(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "sample", targetNamespace = "")
        Sample sample)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param sampleParameterPK
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeSampleParameter", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveSampleParameter")
    @ResponseWrapper(localName = "removeSampleParameterResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveSampleParameterResponse")
    public void removeSampleParameter(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "sampleParameterPK", targetNamespace = "")
        SampleParameterPK sampleParameterPK)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param sampleParameterPK
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSampleParameter", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteSampleParameter")
    @ResponseWrapper(localName = "deleteSampleParameterResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteSampleParameterResponse")
    public void deleteSampleParameter(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "sampleParameterPK", targetNamespace = "")
        SampleParameterPK sampleParameterPK)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param sampleParameter
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifySampleParameter", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifySampleParameter")
    @ResponseWrapper(localName = "modifySampleParameterResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifySampleParameterResponse")
    public void modifySampleParameter(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "sampleParameter", targetNamespace = "")
        SampleParameter sampleParameter)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param elementId
     * @param sessionId
     * @param elementType
     * @return
     *     returns java.util.List<uk.icat3.client.IcatAuthorisation>
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuthorisations", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetAuthorisations")
    @ResponseWrapper(localName = "getAuthorisationsResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetAuthorisationsResponse")
    public List<IcatAuthorisation> getAuthorisations(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "elementId", targetNamespace = "")
        Long elementId,
        @WebParam(name = "elementType", targetNamespace = "")
        ElementType elementType)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param elementId
     * @param toAddFedId
     * @param sessionId
     * @param toAddRole
     * @param elementType
     * @return
     *     returns uk.icat3.client.IcatAuthorisation
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAuthorisation", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddAuthorisation")
    @ResponseWrapper(localName = "addAuthorisationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddAuthorisationResponse")
    public IcatAuthorisation addAuthorisation(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "toAddFedId", targetNamespace = "")
        String toAddFedId,
        @WebParam(name = "toAddRole", targetNamespace = "")
        String toAddRole,
        @WebParam(name = "elementId", targetNamespace = "")
        Long elementId,
        @WebParam(name = "elementType", targetNamespace = "")
        ElementType elementType)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param authorisationId
     * @param sessionId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAuthorisation", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteAuthorisation")
    @ResponseWrapper(localName = "deleteAuthorisationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteAuthorisationResponse")
    public void deleteAuthorisation(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "authorisationId", targetNamespace = "")
        Long authorisationId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param authorisationId
     * @param sessionId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeAuthorisation", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveAuthorisation")
    @ResponseWrapper(localName = "removeAuthorisationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveAuthorisationResponse")
    public void removeAuthorisation(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "authorisationId", targetNamespace = "")
        Long authorisationId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param authorisationId
     * @param sessionId
     * @param toChangetoRole
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateAuthorisation", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.UpdateAuthorisation")
    @ResponseWrapper(localName = "updateAuthorisationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.UpdateAuthorisationResponse")
    public void updateAuthorisation(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "toChangetoRole", targetNamespace = "")
        String toChangetoRole,
        @WebParam(name = "authorisationId", targetNamespace = "")
        Long authorisationId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getKeywordsForUser", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetKeywordsForUser")
    @ResponseWrapper(localName = "getKeywordsForUserResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetKeywordsForUserResponse")
    public List<String> getKeywordsForUser(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param numberReturned
     * @param startKeyword
     * @param sessionId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getKeywordsForUserStartWithMax", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetKeywordsForUserStartWithMax")
    @ResponseWrapper(localName = "getKeywordsForUserStartWithMaxResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetKeywordsForUserStartWithMaxResponse")
    public List<String> getKeywordsForUserStartWithMax(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "startKeyword", targetNamespace = "")
        String startKeyword,
        @WebParam(name = "numberReturned", targetNamespace = "")
        int numberReturned)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param numberReturned
     * @param sessionId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getKeywordsForUserMax", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetKeywordsForUserMax")
    @ResponseWrapper(localName = "getKeywordsForUserMaxResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetKeywordsForUserMaxResponse")
    public List<String> getKeywordsForUserMax(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "numberReturned", targetNamespace = "")
        int numberReturned)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param keywordType
     * @param sessionId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getKeywordsForUserType", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetKeywordsForUserType")
    @ResponseWrapper(localName = "getKeywordsForUserTypeResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetKeywordsForUserTypeResponse")
    public List<String> getKeywordsForUserType(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "keywordType", targetNamespace = "")
        KeywordType keywordType)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param type
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllKeywords", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetAllKeywords")
    @ResponseWrapper(localName = "getAllKeywordsResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetAllKeywordsResponse")
    public List<String> getAllKeywords(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "type", targetNamespace = "")
        KeywordType type)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param sampleName
     * @return
     *     returns java.util.List<uk.icat3.client.Sample>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchSamplesBySampleName", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchSamplesBySampleName")
    @ResponseWrapper(localName = "searchSamplesBySampleNameResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchSamplesBySampleNameResponse")
    public List<Sample> searchSamplesBySampleName(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "sampleName", targetNamespace = "")
        String sampleName)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param sample
     * @return
     *     returns java.util.List<uk.icat3.client.Dataset>
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchDatasetsBySample", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchDatasetsBySample")
    @ResponseWrapper(localName = "searchDatasetsBySampleResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchDatasetsBySampleResponse")
    public List<Dataset> searchDatasetsBySample(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "sample", targetNamespace = "")
        Sample sample)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listDatasetTypes", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ListDatasetTypes")
    @ResponseWrapper(localName = "listDatasetTypesResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ListDatasetTypesResponse")
    public List<String> listDatasetTypes(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listDatasetStatus", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ListDatasetStatus")
    @ResponseWrapper(localName = "listDatasetStatusResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ListDatasetStatusResponse")
    public List<String> listDatasetStatus(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param endRun
     * @param startRun
     * @param instruments
     * @return
     *     returns java.util.List<uk.icat3.client.Datafile>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByRunNumber", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByRunNumber")
    @ResponseWrapper(localName = "searchByRunNumberResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByRunNumberResponse")
    public List<Datafile> searchByRunNumber(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "instruments", targetNamespace = "")
        List<String> instruments,
        @WebParam(name = "startRun", targetNamespace = "")
        float startRun,
        @WebParam(name = "endRun", targetNamespace = "")
        float endRun)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param startIndex
     * @param numberOfResults
     * @param sessionId
     * @param endRun
     * @param startRun
     * @param instruments
     * @return
     *     returns java.util.List<uk.icat3.client.Datafile>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByRunNumberPagination", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByRunNumberPagination")
    @ResponseWrapper(localName = "searchByRunNumberPaginationResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SearchByRunNumberPaginationResponse")
    public List<Datafile> searchByRunNumberPagination(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "instruments", targetNamespace = "")
        List<String> instruments,
        @WebParam(name = "startRun", targetNamespace = "")
        float startRun,
        @WebParam(name = "endRun", targetNamespace = "")
        float endRun,
        @WebParam(name = "startIndex", targetNamespace = "")
        int startIndex,
        @WebParam(name = "numberOfResults", targetNamespace = "")
        int numberOfResults)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns java.util.List<uk.icat3.client.DatafileFormat>
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listDatafileFormats", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ListDatafileFormats")
    @ResponseWrapper(localName = "listDatafileFormatsResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ListDatafileFormatsResponse")
    public List<DatafileFormat> listDatafileFormats(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datasetIds
     * @return
     *     returns java.util.List<uk.icat3.client.Dataset>
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatasets", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetDatasets")
    @ResponseWrapper(localName = "getDatasetsResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetDatasetsResponse")
    public List<Dataset> getDatasets(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datasetIds", targetNamespace = "")
        List<Long> datasetIds)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param investigationId
     * @param dataSet
     * @return
     *     returns uk.icat3.client.Dataset
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDataSet", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.CreateDataSet")
    @ResponseWrapper(localName = "createDataSetResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.CreateDataSetResponse")
    public Dataset createDataSet(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "dataSet", targetNamespace = "")
        Dataset dataSet,
        @WebParam(name = "investigationId", targetNamespace = "")
        Long investigationId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param dataSets
     * @param investigationId
     * @return
     *     returns java.util.List<uk.icat3.client.Dataset>
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDataSets", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.CreateDataSets")
    @ResponseWrapper(localName = "createDataSetsResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.CreateDataSetsResponse")
    public List<Dataset> createDataSets(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "dataSets", targetNamespace = "")
        List<Dataset> dataSets,
        @WebParam(name = "investigationId", targetNamespace = "")
        Long investigationId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param dataSetId
     * @param sessionId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDataSet", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteDataSet")
    @ResponseWrapper(localName = "deleteDataSetResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteDataSetResponse")
    public void deleteDataSet(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "dataSetId", targetNamespace = "")
        Long dataSetId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param datasetParameterPK
     * @param sessionId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDataSetParameter", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteDataSetParameter")
    @ResponseWrapper(localName = "deleteDataSetParameterResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteDataSetParameterResponse")
    public void deleteDataSetParameter(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datasetParameterPK", targetNamespace = "")
        DatasetParameterPK datasetParameterPK)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param dataSet
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifyDataSet", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifyDataSet")
    @ResponseWrapper(localName = "modifyDataSetResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifyDataSetResponse")
    public void modifyDataSet(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "dataSet", targetNamespace = "")
        Dataset dataSet)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param dataSetParameter
     * @param sessionId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifyDataSetParameter", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifyDataSetParameter")
    @ResponseWrapper(localName = "modifyDataSetParameterResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifyDataSetParameterResponse")
    public void modifyDataSetParameter(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "dataSetParameter", targetNamespace = "")
        DatasetParameter dataSetParameter)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datafileId
     * @param sampleId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setDataSetSample", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SetDataSetSample")
    @ResponseWrapper(localName = "setDataSetSampleResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.SetDataSetSampleResponse")
    public void setDataSetSample(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "sampleId", targetNamespace = "")
        Long sampleId,
        @WebParam(name = "datafileId", targetNamespace = "")
        Long datafileId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param dataSetParameter
     * @param sessionId
     * @param datasetId
     * @return
     *     returns uk.icat3.client.DatasetParameter
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addDataSetParameter", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddDataSetParameter")
    @ResponseWrapper(localName = "addDataSetParameterResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddDataSetParameterResponse")
    public DatasetParameter addDataSetParameter(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "dataSetParameter", targetNamespace = "")
        DatasetParameter dataSetParameter,
        @WebParam(name = "datasetId", targetNamespace = "")
        Long datasetId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datasetId
     * @param dataSetParameters
     * @return
     *     returns java.util.List<uk.icat3.client.DatasetParameter>
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addDataSetParameters", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddDataSetParameters")
    @ResponseWrapper(localName = "addDataSetParametersResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddDataSetParametersResponse")
    public List<DatasetParameter> addDataSetParameters(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "dataSetParameters", targetNamespace = "")
        List<DatasetParameter> dataSetParameters,
        @WebParam(name = "datasetId", targetNamespace = "")
        Long datasetId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param dataSetId
     * @param sessionId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeDataSet", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveDataSet")
    @ResponseWrapper(localName = "removeDataSetResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveDataSetResponse")
    public void removeDataSet(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "dataSetId", targetNamespace = "")
        Long dataSetId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param datasetParameterPK
     * @param sessionId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeDataSetParameter", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveDataSetParameter")
    @ResponseWrapper(localName = "removeDataSetParameterResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveDataSetParameterResponse")
    public void removeDataSetParameter(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datasetParameterPK", targetNamespace = "")
        DatasetParameterPK datasetParameterPK)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datafileIds
     * @return
     *     returns java.util.List<uk.icat3.client.Datafile>
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatafiles", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetDatafiles")
    @ResponseWrapper(localName = "getDatafilesResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.GetDatafilesResponse")
    public List<Datafile> getDatafiles(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datafileIds", targetNamespace = "")
        List<Long> datafileIds)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datasetId
     * @param dataFile
     * @return
     *     returns uk.icat3.client.Datafile
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDataFile", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.CreateDataFile")
    @ResponseWrapper(localName = "createDataFileResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.CreateDataFileResponse")
    public Datafile createDataFile(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "dataFile", targetNamespace = "")
        Datafile dataFile,
        @WebParam(name = "datasetId", targetNamespace = "")
        Long datasetId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datasetId
     * @param dataFiles
     * @return
     *     returns java.util.List<uk.icat3.client.Datafile>
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDataFiles", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.CreateDataFiles")
    @ResponseWrapper(localName = "createDataFilesResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.CreateDataFilesResponse")
    public List<Datafile> createDataFiles(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "dataFiles", targetNamespace = "")
        List<Datafile> dataFiles,
        @WebParam(name = "datasetId", targetNamespace = "")
        Long datasetId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datafileId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDataFile", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteDataFile")
    @ResponseWrapper(localName = "deleteDataFileResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteDataFileResponse")
    public void deleteDataFile(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datafileId", targetNamespace = "")
        Long datafileId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param dataFile
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifyDataFile", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifyDataFile")
    @ResponseWrapper(localName = "modifyDataFileResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifyDataFileResponse")
    public void modifyDataFile(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "dataFile", targetNamespace = "")
        Datafile dataFile)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datafileId
     * @param dataFileParameters
     * @return
     *     returns java.util.List<uk.icat3.client.DatafileParameter>
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addDataFileParameters", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddDataFileParameters")
    @ResponseWrapper(localName = "addDataFileParametersResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.AddDataFileParametersResponse")
    public List<DatafileParameter> addDataFileParameters(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "dataFileParameters", targetNamespace = "")
        List<DatafileParameter> dataFileParameters,
        @WebParam(name = "datafileId", targetNamespace = "")
        Long datafileId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param dataFileParameter
     * @param sessionId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws ValidationException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "modifyDataFileParameter", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifyDataFileParameter")
    @ResponseWrapper(localName = "modifyDataFileParameterResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.ModifyDataFileParameterResponse")
    public void modifyDataFileParameter(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "dataFileParameter", targetNamespace = "")
        DatafileParameter dataFileParameter)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception, ValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datafileParameterPK
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDataFileParameter", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteDataFileParameter")
    @ResponseWrapper(localName = "deleteDataFileParameterResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DeleteDataFileParameterResponse")
    public void deleteDataFileParameter(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datafileParameterPK", targetNamespace = "")
        DatafileParameterPK datafileParameterPK)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datafileId
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeDataFile", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveDataFile")
    @ResponseWrapper(localName = "removeDataFileResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveDataFileResponse")
    public void removeDataFile(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datafileId", targetNamespace = "")
        Long datafileId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datafileParameterPK
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeDataFileParameter", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveDataFileParameter")
    @ResponseWrapper(localName = "removeDataFileParameterResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.RemoveDataFileParameterResponse")
    public void removeDataFileParameter(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datafileParameterPK", targetNamespace = "")
        DatafileParameterPK datafileParameterPK)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datafileId
     * @return
     *     returns java.lang.String
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(name = "URL", targetNamespace = "")
    @RequestWrapper(localName = "downloadDatafile", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DownloadDatafile")
    @ResponseWrapper(localName = "downloadDatafileResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DownloadDatafileResponse")
    public String downloadDatafile(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datafileId", targetNamespace = "")
        Long datafileId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datasetId
     * @return
     *     returns java.lang.String
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(name = "URL", targetNamespace = "")
    @RequestWrapper(localName = "downloadDataset", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DownloadDataset")
    @ResponseWrapper(localName = "downloadDatasetResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DownloadDatasetResponse")
    public String downloadDataset(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datasetId", targetNamespace = "")
        Long datasetId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datafileIds
     * @return
     *     returns java.lang.String
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(name = "URL", targetNamespace = "")
    @RequestWrapper(localName = "downloadDatafiles", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DownloadDatafiles")
    @ResponseWrapper(localName = "downloadDatafilesResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.DownloadDatafilesResponse")
    public String downloadDatafiles(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datafileIds", targetNamespace = "")
        List<Long> datafileIds)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datafileIds
     * @return
     *     returns uk.icat3.client.DownloadInfo
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadInfo", targetNamespace = "")
    @RequestWrapper(localName = "checkDatafileDownloadAccess", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.CheckDatafileDownloadAccess")
    @ResponseWrapper(localName = "checkDatafileDownloadAccessResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.CheckDatafileDownloadAccessResponse")
    public DownloadInfo checkDatafileDownloadAccess(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datafileIds", targetNamespace = "")
        List<Long> datafileIds)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param datasetId
     * @return
     *     returns uk.icat3.client.DownloadInfo
     * @throws NoSuchObjectFoundException_Exception
     * @throws InsufficientPrivilegesException_Exception
     * @throws SessionException_Exception
     */
    @WebMethod
    @WebResult(name = "downloadInfo", targetNamespace = "")
    @RequestWrapper(localName = "checkDatasetDownloadAccess", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.CheckDatasetDownloadAccess")
    @ResponseWrapper(localName = "checkDatasetDownloadAccessResponse", targetNamespace = "client.icat3.uk", className = "uk.icat3.client.CheckDatasetDownloadAccessResponse")
    public DownloadInfo checkDatasetDownloadAccess(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "datasetId", targetNamespace = "")
        Long datasetId)
        throws InsufficientPrivilegesException_Exception, NoSuchObjectFoundException_Exception, SessionException_Exception
    ;

}
