
package uk.icat3.client.admin;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "SessionException", targetNamespace = "admin.client.icat3.uk")
public class SessionException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private uk.icat3.client.SessionException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SessionException(String message, uk.icat3.client.SessionException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SessionException(String message, uk.icat3.client.SessionException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: uk.icat3.client.SessionException
     */
    public uk.icat3.client.SessionException getFaultInfo() {
        return faultInfo;
    }

}
