
package uk.icat3.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "InsufficientPrivilegesException", targetNamespace = "client.icat3.uk")
public class InsufficientPrivilegesException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InsufficientPrivilegesException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InsufficientPrivilegesException_Exception(String message, InsufficientPrivilegesException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InsufficientPrivilegesException_Exception(String message, InsufficientPrivilegesException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: uk.icat3.client.InsufficientPrivilegesException
     */
    public InsufficientPrivilegesException getFaultInfo() {
        return faultInfo;
    }

}
