/*
 * Copyright 2012 Diamond Light Source Ltd.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.icat3.client.admin;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.4-b01- Generated
 * source version: 2.1
 * 
 */
@WebFault(name = "SessionException", targetNamespace = "admin.client.icat3.uk")
public class SessionException extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private uk.icat3.client.SessionException faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public SessionException(String message,
			uk.icat3.client.SessionException faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public SessionException(String message,
			uk.icat3.client.SessionException faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: uk.icat3.client.SessionException
	 */
	public uk.icat3.client.SessionException getFaultInfo() {
		return faultInfo;
	}

}
